package com;
// Generated Jul 20, 2016 11:27:06 AM by Hibernate Tools 4.3.1



/**
 * Blogdata generated by hbm2java
 */
public class Blogdata  implements java.io.Serializable {


     private Integer bid;
     private String bcontent;
     private String bintro;
     private String btype;

    public Blogdata() {
    }

    public Blogdata(String bcontent, String bintro, String btype) {
       this.bcontent = bcontent;
       this.bintro = bintro;
       this.btype = btype;
    }
   
    public Integer getBid() {
        return this.bid;
    }
    
    public void setBid(Integer bid) {
        this.bid = bid;
    }
    public String getBcontent() {
        return this.bcontent;
    }
    
    public void setBcontent(String bcontent) {
        this.bcontent = bcontent;
    }
    public String getBintro() {
        return this.bintro;
    }
    
    public void setBintro(String bintro) {
        this.bintro = bintro;
    }
    public String getBtype() {
        return this.btype;
    }
    
    public void setBtype(String btype) {
        this.btype = btype;
    }




}


