package com;
// Generated Jul 20, 2016 11:27:06 AM by Hibernate Tools 4.3.1



/**
 * Querydata generated by hbm2java
 */
public class Querydata  implements java.io.Serializable {


     private Integer qid;
     private String qbody;
     private String qtopic;

    public Querydata() {
    }

    public Querydata(String qbody, String qtopic) {
       this.qbody = qbody;
       this.qtopic = qtopic;
    }
   
    public Integer getQid() {
        return this.qid;
    }
    
    public void setQid(Integer qid) {
        this.qid = qid;
    }
    public String getQbody() {
        return this.qbody;
    }
    
    public void setQbody(String qbody) {
        this.qbody = qbody;
    }
    public String getQtopic() {
        return this.qtopic;
    }
    
    public void setQtopic(String qtopic) {
        this.qtopic = qtopic;
    }




}


